#### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [2]:
import pandas as pd

In [3]:
## Series
## A Pandas series is a 1-d array like object which can store any datatype.
### It is similar to a column in table
import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series\n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [4]:
### Create a series from dictionary 
data={'a':1,'b':2,'c':3,'d':4}
series_dict= pd.Series(data)
print(series_dict)

a    1
b    2
c    3
d    4
dtype: int64

In [5]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [6]:
data=['Parth','Ansh','Sargam','Akshita']
roll_No=[11,2,55,13]
pd.Series(data,index=roll_No)

11      Parth
2        Ansh
55     Sargam
13    Akshita
dtype: str

In [18]:
### Dataframe using dictionary
data={
  'Name':['Parth','Akshita','SAARGAM'],
  'Age':[22,23,24],
  'city':["Lucknow","Maharajganj","Gonda"]
}

df11=pd.DataFrame(data)
print(df11)
print(type(df11))

      Name  Age         city
0    Parth   22      Lucknow
1  Akshita   23  Maharajganj
2  SAARGAM   24        Gonda
<class 'pandas.DataFrame'>

In [53]:
### Create a data Frame from a list of dictionaries
data=[
  {'Name':'Parth','Age':22,'City':'Lucknow'},
  {'Name':'Sargam','Age':23,'City':'Gonda'},
  {'Name':'Akshita','Age':21,'City':'Gorakhpur'},
]

df=pd.DataFrame(data)
print(df)

      Name  Age       City
0    Parth   22    Lucknow
1   Sargam   23      Gonda
2  Akshita   21  Gorakhpur

In [54]:
df=pd.read_csv('data.csv')
df.head(10)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North
5  2023-01-06        B   54.0  Product3  192.0   West
6  2023-01-07        A   16.0  Product1  936.0   East
7  2023-01-08        C   89.0  Product1  488.0   West
8  2023-01-09        C   37.0  Product3  772.0   West
9  2023-01-10        A   22.0  Product2  834.0   West

In [56]:
df.tail(5)

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [76]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [57]:
### Accessing data from dataframe
df11

      Name  Age         city
0    Parth   23      Lucknow
1  Akshita   24  Maharajganj
2  SAARGAM   25        Gonda

In [58]:
df11['Name']
print(type(df11['Name']))

<class 'pandas.Series'>

In [59]:
df11.loc[0] ## for row index

Name      Parth
Age          23
city    Lucknow
Name: 0, dtype: object

In [60]:
df11.iloc[1]

Name        Akshita
Age              24
city    Maharajganj
Name: 1, dtype: object

In [61]:
## Accesing a specified element
df11.at[1,'Age']

np.int64(24)

In [62]:
df11

      Name  Age         city
0    Parth   23      Lucknow
1  Akshita   24  Maharajganj
2  SAARGAM   25        Gonda

In [63]:
df11.at[2,'city']

'Gonda'

In [64]:
## Accesing using iat is different from at
df11.iat[1,2]

'Maharajganj'

In [65]:
### Data Manipukations with data frames
df11

      Name  Age         city
0    Parth   23      Lucknow
1  Akshita   24  Maharajganj
2  SAARGAM   25        Gonda

In [66]:
df11['Salary']=[50000,60000,70000]
df11

      Name  Age         city  Salary
0    Parth   23      Lucknow   50000
1  Akshita   24  Maharajganj   60000
2  SAARGAM   25        Gonda   70000

In [67]:
## Remove a coloumn
df11.drop('Salary',axis=1)

      Name  Age         city
0    Parth   23      Lucknow
1  Akshita   24  Maharajganj
2  SAARGAM   25        Gonda

In [68]:
df11

      Name  Age         city  Salary
0    Parth   23      Lucknow   50000
1  Akshita   24  Maharajganj   60000
2  SAARGAM   25        Gonda   70000

In [69]:
df11.drop('Salary',axis=1,inplace=True)## permanently deletes the coloumn

In [70]:
df11

      Name  Age         city
0    Parth   23      Lucknow
1  Akshita   24  Maharajganj
2  SAARGAM   25        Gonda

In [71]:
### Add 1 age to the coloumn
df11['Age']= df11['Age']+1
df11

      Name  Age         city
0    Parth   24      Lucknow
1  Akshita   25  Maharajganj
2  SAARGAM   26        Gonda

In [72]:
df11.drop(0)

      Name  Age         city
1  Akshita   25  Maharajganj
2  SAARGAM   26        Gonda

In [73]:
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North